### ISSUE TITLE
feature extraction

### ISSUE THREAD

**Issue by fangliuwh** [asvspoof/ASVspoof2019_system#4]
maybe one more question: do you have the feature extraction code? It seems that the data loader loads precomputed features from npy file.

**Comment by braveheartwithlove** [comment]
@DeeDive  Same question here. Is that ok to put one of the feature extraction code here?
Thanks!

**Comment by DeeDive** [comment]
Hi @fangliuwh  and @braveheartwithlove, sorry for the late response. Recent lockdown makes everything hard. I updated the codes just now. Feel free to ask if you have further issues.

Best

**Comment by DeeDive** [comment]
Closed. Feel free to ask if you have further issues.
