### ISSUE TITLE
Missing loss.py file?

### ISSUE THREAD

**Issue by mesut92** [asvspoof/ASVspoof2019_system#8]
Hi
I guess, there is missing file(loss.py) in source code.

```
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    from loss import FocalLoss
ModuleNotFoundError: No module named 'loss'
```

**Comment by DeeDive** [comment]
Hi @mesut92 , sorry for the late reply. I've added the missing file. Feel free to ask if you have further issues.
